name: Link Check

on:
  schedule:
    - cron: "00 8 * * *" # 0800 UTC is 0400 AM EDT
  repository_dispatch:
  workflow_dispatch:
    inputs:
      ignorePattern:
        description: 'a pattern provided to grep for files/directories to ignore'
        required: false
        default: '^website/'
        type: string
      site_git_ref:
        description: 'git ref, a SHA commit or branch or tag, for the published HTML content'
        required: true
        default: 'github-pages'
        type: string
      site_git_ref_path:
        description: 'the subdirectory to check out git ref and check links in website content'
        required: true
        default: 'published'
        type: string
      linkcheck_create_issue:
        description: 'create new GitHub issue if broken links found'
        required: false
        default: true
        type: boolean

permissions:
  contents: read
  issues: write

jobs:
  schedule-validate-repo-markdown-links:
    uses: ./.github/workflows/workflow-validate-repo-markdown.yml
    if: github.event_name != 'workflow_dispatch'
    with:
      ignorePattern: '^website/'
      linkcheck_create_issue: true
  schedule-validate-repo-markdown-links-debug:
    uses: ./.github/workflows/workflow-validate-repo-markdown.yml
    if: github.event_name == 'workflow_dispatch'
    with:
      ignorePattern: ${{ github.event.inputs.ignorePattern }}
      linkcheck_create_issue: ${{ contains('true', github.event.inputs.linkcheck_create_issue) }}
  schedule-validate-website-links:
    uses: ./.github/workflows/workflow-validate-website-content.yml
    if: github.event_name != 'workflow_dispatch'
    with:
      site_git_ref: 'github-pages'
      site_git_ref_path: 'published'
      linkcheck_create_issue: true
  schedule-validate-website-links-debug:
    uses: ./.github/workflows/workflow-validate-website-content.yml
    if: github.event_name == 'workflow_dispatch'
    with:
      site_git_ref: ${{ github.event.inputs.site_git_ref }}
      site_git_ref_path: ${{ github.event.inputs.site_git_ref_path }}
      linkcheck_create_issue: ${{ contains('true', github.event.inputs.linkcheck_create_issue) }}
